name=DevBoxSDK
version=0.0.1
author=Daniil Tsedik
maintainer=Daniil Tsedik
sentence=Drivers and common hardware code for DevBox portable console.
paragraph=
category=Other
url=none
architectures=esp32